### ISSUE TITLE
Resizing image to fill area = bad URI error from WEBrick

### ISSUE THREAD

**Issue by alekseyg** [jekyll-assets/jekyll-assets#159]
When using the resize to fill area feature, WEBrick refuses to serve the resulting image. My guess is because `^` is probably not a good character to put in the URL.

input:
```liquid
{% image example.jpg [resize:400x400^] %}
```

output:
```html
<img src="/assets/example-400x400^-560372da9018331580321f8d39286377.jpg">
```

HTTP response:
```
Bad Request

bad URI `/assets/example-400x400^-560372da9018331580321f8d39286377.jpg'.
WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) at alekseys-macbook-pro.local:4000
```

This happens on both, 0.14.0 and 1.0.0.pre.alpha1

**Comment by j15e** [comment]
Good point. Suggestion : hash the resize parameters

**Comment by envygeeks** [comment]
What version of Jekyll is this so I can replicate it and try to fix it for the 1.0.0 release?

**Comment by alekseyg** [comment]
Jekyll 2.5.3. Ruby 2.1.5p273. Here's my Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.3.8)
    autoprefixer-rails (5.2.0)
      execjs
      json
    blankslate (2.1.2.4)
    bootstrap-sass (3.3.4.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    classifier-reborn (2.0.3)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorator (0.1)
    execjs (2.5.2)
    fast-stemmer (1.0.2)
    fastimage (1.7.0)
      addressable (~> 2.3, >= 2.3.5)
    ffi (1.9.8)
    hike (1.2.3)
    hitimes (1.2.2)
    jekyll (2.5.3)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-assets (1.0.0.pre.alpha1)
      fastimage (~> 1.6)
      jekyll (~> 2.0)
      mini_magick (~> 4.1)
      sass (~> 3.2)
      sprockets (~> 2.10)
      sprockets-helpers
      sprockets-sass
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-gist (1.2.1)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.2.1)
      listen (~> 2.7)
    json (1.8.3)
    kramdown (1.7.0)
    liquid (2.6.2)
    listen (2.10.0)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    mini_magick (4.2.7)
    multi_json (1.11.1)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.11)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rack (1.6.1)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.3.1)
    safe_yaml (1.0.4)
    sass (3.4.14)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (1.3.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    toml (0.1.2)
      parslet (~> 1.5.0)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-sass
  jekyll (~> 2.5.3)
  jekyll-assets (~> 1.0.0.pre.alpha1)
  uglifier
```

**Comment by envygeeks** [comment]
It looks like this is fixed in the latest jekyll-assets so it could have been a Jekyll issue or old webrick issue, I'll flag this for testing on the new jekyll-assets rather than fix it here since that one will progress faster with jekyll3 over this weekend.

**Comment by alekseyg** [comment]
I finally got around to testing it with the latest gems installed. The issue still persists with Ruby 2.2.3, WEBrick 1.3.1 (latest stable, but released in 2011), Jekyll 2.5.3, and Jekyll-Assets 1.0.0. My guess is that it is a WEBrick issue, but that means there's then no way to test your website using a stable release of Jekyll until you upload it to a more production like server. Otherwise, I need to upgrade my websites to Jekyll 3 beta. Am I right?

**Comment by envygeeks** [comment]
Current master (the best) only supports Jekyll 3 because we make extensive use of hooks.

**Comment by alekseyg** [comment]
OK thanks. This particular site I'm working on is rather image heavy, but uses very little of other Jekyll stuff, so it should be safe to upgrade it. :)
